//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Fotokiosk
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Запись время.
    /// </summary>
    // *** Start programmer edit section *** (ЗаписьВремя CustomAttributes)

    // *** End programmer edit section *** (ЗаписьВремя CustomAttributes)
    [AutoAltered()]
    [Caption("Запись время")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаписьВремяE", new string[] {
            "Время as \'Время\'",
            "Статус as \'Статус\'",
            "Дата as \'Дата\'",
            "ПрайсЛист as \'Прайс лист\'",
            "ПрайсЛист.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "ПрайсЛист.Наименование"})]
    [MasterViewDefineAttribute("ЗаписьВремяE", "ПрайсЛист", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("ЗаписьВремяL", new string[] {
            "Время as \'Время\'",
            "Статус as \'Статус\'",
            "Дата as \'Дата\'",
            "ПрайсЛист.Наименование as \'Наименование\'"})]
    public class ЗаписьВремя : ICSSoft.STORMNET.DataObject
    {
        
        private string fВремя;
        
        private IIS.Fotokiosk.Статусы fСтатус;
        
        private System.DateTime fДата;
        
        private IIS.Fotokiosk.ПрайсЛист fПрайсЛист;
        
        // *** Start programmer edit section *** (ЗаписьВремя CustomMembers)

        // *** End programmer edit section *** (ЗаписьВремя CustomMembers)

        
        /// <summary>
        /// Время.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьВремя.Время CustomAttributes)

        // *** End programmer edit section *** (ЗаписьВремя.Время CustomAttributes)
        [StrLen(255)]
        public virtual string Время
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьВремя.Время Get start)

                // *** End programmer edit section *** (ЗаписьВремя.Время Get start)
                string result = this.fВремя;
                // *** Start programmer edit section *** (ЗаписьВремя.Время Get end)

                // *** End programmer edit section *** (ЗаписьВремя.Время Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьВремя.Время Set start)

                // *** End programmer edit section *** (ЗаписьВремя.Время Set start)
                this.fВремя = value;
                // *** Start programmer edit section *** (ЗаписьВремя.Время Set end)

                // *** End programmer edit section *** (ЗаписьВремя.Время Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьВремя.Дата CustomAttributes)

        // *** End programmer edit section *** (ЗаписьВремя.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьВремя.Дата Get start)

                // *** End programmer edit section *** (ЗаписьВремя.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ЗаписьВремя.Дата Get end)

                // *** End programmer edit section *** (ЗаписьВремя.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьВремя.Дата Set start)

                // *** End programmer edit section *** (ЗаписьВремя.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ЗаписьВремя.Дата Set end)

                // *** End programmer edit section *** (ЗаписьВремя.Дата Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьВремя.Статус CustomAttributes)

        // *** End programmer edit section *** (ЗаписьВремя.Статус CustomAttributes)
        public virtual IIS.Fotokiosk.Статусы Статус
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьВремя.Статус Get start)

                // *** End programmer edit section *** (ЗаписьВремя.Статус Get start)
                IIS.Fotokiosk.Статусы result = this.fСтатус;
                // *** Start programmer edit section *** (ЗаписьВремя.Статус Get end)

                // *** End programmer edit section *** (ЗаписьВремя.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьВремя.Статус Set start)

                // *** End programmer edit section *** (ЗаписьВремя.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (ЗаписьВремя.Статус Set end)

                // *** End programmer edit section *** (ЗаписьВремя.Статус Set end)
            }
        }
        
        /// <summary>
        /// Запись время.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьВремя.ПрайсЛист CustomAttributes)

        // *** End programmer edit section *** (ЗаписьВремя.ПрайсЛист CustomAttributes)
        [PropertyStorage(new string[] {
                "ПрайсЛист"})]
        [NotNull()]
        public virtual IIS.Fotokiosk.ПрайсЛист ПрайсЛист
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьВремя.ПрайсЛист Get start)

                // *** End programmer edit section *** (ЗаписьВремя.ПрайсЛист Get start)
                IIS.Fotokiosk.ПрайсЛист result = this.fПрайсЛист;
                // *** Start programmer edit section *** (ЗаписьВремя.ПрайсЛист Get end)

                // *** End programmer edit section *** (ЗаписьВремя.ПрайсЛист Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьВремя.ПрайсЛист Set start)

                // *** End programmer edit section *** (ЗаписьВремя.ПрайсЛист Set start)
                this.fПрайсЛист = value;
                // *** Start programmer edit section *** (ЗаписьВремя.ПрайсЛист Set end)

                // *** End programmer edit section *** (ЗаписьВремя.ПрайсЛист Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаписьВремяE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьВремяE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьВремяE", typeof(IIS.Fotokiosk.ЗаписьВремя));
                }
            }
            
            /// <summary>
            /// "ЗаписьВремяL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьВремяL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьВремяL", typeof(IIS.Fotokiosk.ЗаписьВремя));
                }
            }
        }
    }
}
