//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Fotokiosk
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расход материад.
    /// </summary>
    // *** Start programmer edit section *** (РасходМатериад CustomAttributes)

    // *** End programmer edit section *** (РасходМатериад CustomAttributes)
    [AutoAltered()]
    [Caption("Расход материад")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РасходМатериадE", new string[] {
            "Количество as \'Количество\'",
            "Материал as \'Материал\'",
            "Материал.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Материал.Наименование"})]
    [MasterViewDefineAttribute("РасходМатериадE", "Материал", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class РасходМатериад : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private IIS.Fotokiosk.Материал fМатериал;
        
        private IIS.Fotokiosk.Трудозатраты fТрудозатраты;
        
        // *** Start programmer edit section *** (РасходМатериад CustomMembers)

        // *** End programmer edit section *** (РасходМатериад CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (РасходМатериад.Количество CustomAttributes)

        // *** End programmer edit section *** (РасходМатериад.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (РасходМатериад.Количество Get start)

                // *** End programmer edit section *** (РасходМатериад.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (РасходМатериад.Количество Get end)

                // *** End programmer edit section *** (РасходМатериад.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасходМатериад.Количество Set start)

                // *** End programmer edit section *** (РасходМатериад.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (РасходМатериад.Количество Set end)

                // *** End programmer edit section *** (РасходМатериад.Количество Set end)
            }
        }
        
        /// <summary>
        /// Расход материад.
        /// </summary>
        // *** Start programmer edit section *** (РасходМатериад.Материал CustomAttributes)

        // *** End programmer edit section *** (РасходМатериад.Материал CustomAttributes)
        [PropertyStorage(new string[] {
                "Материал"})]
        [NotNull()]
        public virtual IIS.Fotokiosk.Материал Материал
        {
            get
            {
                // *** Start programmer edit section *** (РасходМатериад.Материал Get start)

                // *** End programmer edit section *** (РасходМатериад.Материал Get start)
                IIS.Fotokiosk.Материал result = this.fМатериал;
                // *** Start programmer edit section *** (РасходМатериад.Материал Get end)

                // *** End programmer edit section *** (РасходМатериад.Материал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасходМатериад.Материал Set start)

                // *** End programmer edit section *** (РасходМатериад.Материал Set start)
                this.fМатериал = value;
                // *** Start programmer edit section *** (РасходМатериад.Материал Set end)

                // *** End programmer edit section *** (РасходМатериад.Материал Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Fotokiosk.Трудозатраты.
        /// </summary>
        // *** Start programmer edit section *** (РасходМатериад.Трудозатраты CustomAttributes)

        // *** End programmer edit section *** (РасходМатериад.Трудозатраты CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Трудозатраты"})]
        public virtual IIS.Fotokiosk.Трудозатраты Трудозатраты
        {
            get
            {
                // *** Start programmer edit section *** (РасходМатериад.Трудозатраты Get start)

                // *** End programmer edit section *** (РасходМатериад.Трудозатраты Get start)
                IIS.Fotokiosk.Трудозатраты result = this.fТрудозатраты;
                // *** Start programmer edit section *** (РасходМатериад.Трудозатраты Get end)

                // *** End programmer edit section *** (РасходМатериад.Трудозатраты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасходМатериад.Трудозатраты Set start)

                // *** End programmer edit section *** (РасходМатериад.Трудозатраты Set start)
                this.fТрудозатраты = value;
                // *** Start programmer edit section *** (РасходМатериад.Трудозатраты Set end)

                // *** End programmer edit section *** (РасходМатериад.Трудозатраты Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РасходМатериадE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасходМатериадE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасходМатериадE", typeof(IIS.Fotokiosk.РасходМатериад));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of РасходМатериад.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfРасходМатериад CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfРасходМатериад CustomAttributes)
    public class DetailArrayOfРасходМатериад : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Fotokiosk.DetailArrayOfРасходМатериад members)

        // *** End programmer edit section *** (IIS.Fotokiosk.DetailArrayOfРасходМатериад members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type РасходМатериад by index.
        /// </summary>
        /// <summary>
        /// Adds object with type РасходМатериад.
        /// </summary>
        public DetailArrayOfРасходМатериад(IIS.Fotokiosk.Трудозатраты fТрудозатраты) : 
                base(typeof(РасходМатериад), ((ICSSoft.STORMNET.DataObject)(fТрудозатраты)))
        {
        }
        
        public IIS.Fotokiosk.РасходМатериад this[int index]
        {
            get
            {
                return ((IIS.Fotokiosk.РасходМатериад)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Fotokiosk.РасходМатериад dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
